comment/urls.py
from django.conf.urls import url
from . import views

app_name = 'comment'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^(?P<pk>[0-9]+)/add-comment/$', views.Comment_Create.as_view(), name='add-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/edit-comment/$', views.Comment_Update.as_view(), name='edit-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/delete-comment/$', views.Comment_Delete.as_view(), name='delete-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/comment-like/$', views.Comment_Like.as_view(), name='like-comment'),
    url(r'^(?P<pk>[0-9]+)/comment-likes-list/$', views.Comment_Likes_List.as_view(), name='like-list-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/comment-vote-up/$', views.Comment_Vote_Up.as_view(), name='vote-up-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/comment-vote-down/$', views.Comment_Vote_Down.as_view(), name='vote-down-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/report-comment/$', views.Comment_Report.as_view(), name='report-comment'),
    url(r'^(?P<pk>[0-9]+)/disable-comment/$', views.Comment_Enable_Disable_Page.as_view(), name='disable-comment'),
    url(r'^(?P<pk>[0-9]+)/disable-comment-confirm/$', views.Comment_Enable_Disable.as_view(), name='disable-comment-confirm'),
    url(r'^(?P<pk>[0-9]+)/remove-comment-flags/$', views.Comment_Remove_Flags_Page.as_view(), name='remove-comment-flags'),
    url(r'^(?P<pk>[0-9]+)/remove-comment-flags-confirm/$', views.Comment_Remove_Flags.as_view(), name='remove-comment-flags-confirm'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/accept-answer/$', views.Accept_Answer.as_view(), name='accept-answer'),
]

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='user-login'),
    url(r'^logout/$', views.user_logout, name='user-logout'),
    url(r'^activate/$', views.activate, name='activate'),
    url(r'^resend-username/$', views.resend_username, name='resend-username'),
    url(r'^reset-password/$', views.reset_password, name='reset-password'),
    url(r'^reset-password-auth/$', views.reset_password_auth, name='reset-password-auth'),
    url(r'^reset-password-confirm/$', views.reset_password_confirm, name='reset-password-confirm'),
    url(r'^profile/(?P<user>[A-Za-z0-9]+)$', views.profile_info, name='profile'),    
    url(r'^edit-profile/(?P<user>[A-Za-z0-9]+)$', views.edit_profile_info, name='edit-profile'),    
    url(r'^delete-profile/$', views.delete_profile_and_user, name='delete-profile'),    
    url(r'^delete-profile-confirm/$', views.delete_profile_and_user_confirm, name='delete-profile-confirm'),    
    url(r'^flagged-posts/$', views.flagged_posts_view, name='flagged-posts'),    
    url(r'^staff/$', views.staff, name='staff'), 
    url(r'^update-staff/(?P<user>[A-Za-z0-9]+)', views.update_staff_status, name='update-staff'),
    url(r'^update-active/(?P<user>[A-Za-z0-9]+)', views.update_active_status, name='update-active'),

    # URL links for class-based views 
    url(r'^$', views.Index_View.as_view(), name='index'),
    url(r'^topics/$', views.Topics_View.as_view(), name='topics'),
    url(r'^topics/(?P<topic>[A-Za-z0-9]+)', views.Posts_With_Same_Topic_View.as_view(), name='topic'),
    
    url(r'^page-not-found/', views.pageNotFound, name='page-not-found'), 

]

post/urls.py
from django.conf.urls import url
from . import views
# from django.contrib.admin.views.decorators import staff_member_required

app_name = 'post'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^(?P<pk>[0-9]+)/$', views.Show_Post_View.as_view(), name='show-post'),
    url(r'^add-post/$', views.Post_Create.as_view(), name='add-post'),
    url(r'^(?P<pk>[0-9]+)/edit-post/$', views.Post_Update.as_view(), name='edit-post'),
    url(r'^(?P<pk>[0-9]+)/delete-post/$', views.Post_Delete.as_view(), name='delete-post'),
    url(r'^(?P<pk>[0-9]+)/like/$', views.Post_Like.as_view(), name='like-post'),
    url(r'^(?P<pk>[0-9]+)/post-likes-list/$', views.Post_Likes_List.as_view(), name='like-list-post'),
    url(r'^(?P<pk>[0-9]+)/post-vote-up/$', views.Post_Vote_Up.as_view(), name='vote-up-post'),
    url(r'^(?P<pk>[0-9]+)/post-vote-down/$', views.Post_Vote_Down.as_view(), name='vote-down-post'),
    url(r'^(?P<pk>[0-9]+)/report-post/$', views.Post_Report.as_view(), name='report-post'),
    url(r'^(?P<pk>[0-9]+)/disable-post/$', views.Post_Enable_Disable_Page.as_view(), name='disable-post'),
    url(r'^(?P<pk>[0-9]+)/disable-post-confirm/$', views.Post_Enable_Disable.as_view(), name='disable-post-confirm'),
    url(r'^(?P<pk>[0-9]+)/remove-post-flags/$', views.Post_Remove_Flags_Page.as_view(), name='remove-post-flags'),
    url(r'^(?P<pk>[0-9]+)/remove-post-flags-confirm/$', views.Post_Remove_Flags.as_view(), name='remove-post-flags-confirm'),
    url(r'^(?P<pk>[0-9]+)/open-comments/$', views.Post_Open_Comments.as_view(), name='open-comments'),
]

qa_forums/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from main.views import pageNotFound
from django.conf.urls import handler404, handler500
from main import views

urlpatterns = [

    url(r'^admin/', admin.site.urls),

    # include all the other URL files from the other apps 
    url(r'^', include('post.urls')),
    url(r'^', include('comment.urls')),
    url(r'^', include('reply.urls')),
    url(r'^', include('main.urls')),
    
    url(r'^page-not-found/', pageNotFound)
] 

# urls for any images uploaded by user
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# handling errors in urls
handler404 = views.error_404
handler500 = views.error_500

reply/urls.py
from django.conf.urls import url
from . import views

app_name = 'reply'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^(?P<post_pk>[0-9]+)/(?P<comment_pk>[0-9]+)/add-reply/$', views.Reply_Create.as_view(), name='add-reply'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/edit-reply/$', views.Reply_Update.as_view(), name='edit-reply'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/delete-reply/$', views.Reply_Delete.as_view(), name='delete-reply'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/reply-like/$', views.Reply_Like.as_view(), name='like-reply'),
    url(r'^(?P<pk>[0-9]+)/reply-likes-list/$', views.Reply_Likes_List.as_view(), name='like-list-reply'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/report-reply/$', views.Reply_Report.as_view(), name='report-reply'),
    url(r'^(?P<pk>[0-9]+)/disable-reply/$', views.Reply_Enable_Disable_Page.as_view(), name='disable-reply'),
    url(r'^(?P<pk>[0-9]+)/disable-reply-confirm/$', views.Reply_Enable_Disable.as_view(), name='disable-reply-confirm'),
    url(r'^(?P<pk>[0-9]+)/remove-reply-flags/$', views.Reply_Remove_Flags_Page.as_view(), name='remove-reply-flags'),
    url(r'^(?P<pk>[0-9]+)/remove-reply-flags-confirm/$', views.Reply_Remove_Flags.as_view(), name='remove-reply-flags-confirm'),
    
]

main/views.py
from random import randint
from django.views import generic
from django.shortcuts import render
from .models import UserProfile, User
from post.models import Post 
from comment.models import Comment
from reply.models import Reply
from django.urls import reverse
from main.forms import UserForm, UserProfileForm, UserUpdateForm, UserProfileUpdateForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.http import HttpResponse
from django.conf import settings
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from .validators import validate_password
import string
import random
from django.core.paginator import Paginator

# registers a new user, sends them an email and saves their profile in the database
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and  profile_form.is_valid():
            user = user_form.save(commit=False) # don't save it in the database yet 

            user.set_password(user.password) # set_password function ensures hashing before saving
            user.is_active = False
            user.save()

            profile = profile_form.save(commit=False) # don't save it in the database yet
            profile.user = user # sets the one to one relationship 
            profile.activationCode = randint(1000, 9999)

            if 'profilePicture' in request.FILES:
                profile.profilePicture = request.FILES['profilePicture']
                
            registered = True
            profile.save()

            # emailing the user using a html template. if the template doesn't work, a txt file gets used as an alternative 
            subject = 'Welcome! - Intelligent Q&A Forums'
            email_to = [user.email] 
            with open(settings.BASE_DIR + "/main/templates/main/authentication/sign_up_email.txt") as temp:
                sign_up_email = temp.read()
            email = EmailMultiAlternatives(
                subject=subject, 
                body=sign_up_email,
                from_email=settings.EMAIL_HOST_USER,
                to=email_to
            )
            html = get_template("main/authentication/sign_up_email.html").render({'user': user, 'activationCode': profile.activationCode})
            email.attach_alternative(html, "text/html")
            email.send()

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(request, 'main/authentication/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

# logs in an existing user 
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)

        if user: 
            if user.is_active:
                login(request, user)

                # creating a userProfile object for superuser when they log in for the first time. (admins are created through the command line so we have to manually create their userProfile)
                if user.is_superuser:
                    try:
                        userProfile = UserProfile.objects.get(user=user)
                    except UserProfile.DoesNotExist:
                        userProfile = UserProfile.objects.create(user=user)
                        userProfile.save()

                # url to redirect to after logging in
                url_to_redirect_to = request.POST.get('next_url')
                if url_to_redirect_to != 'None/':
                    return HttpResponseRedirect('/' + url_to_redirect_to)

                return HttpResponseRedirect(reverse('main:index'))
            else:
                return render(request, 'main/authentication/login.html', {'error': 'Sorry, unable to log you in.'})
        else:
            return render(request, 'main/authentication/login.html', {'error': 'Sorry, unable to log you in.'})
    else:
        url_to_redirect_to = request.GET.get('next')
        return render(request, 'main/authentication/login.html', {'next_url': url_to_redirect_to})

# activates a user that has just signed up
def activate(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        activationCode = request.POST.get('activationCode')
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = None 
        
        if user:
            userProfile = UserProfile.objects.get(user=user)

            if activationCode == userProfile.activationCode: 
                user.is_active = True 
                user.save()
                # changing the activationCode so the user won't be able to activate themselves when Admin disables them.
                userProfile.activationCode = randint(1000, 9999)
                userProfile.save()
                return render(request, 'main/authentication/activate.html', {'activation_success': 'Success! Your account is now activated!'})
            else: 
                return render(request, 'main/authentication/activate.html', {'error': 'Sorry, unable to activate your account.'})

        else:
            return render(request, 'main/authentication/activate.html', {'error': 'Sorry, unable to activate your account.'})
    else:
        return render(request, 'main/authentication/activate.html', {})

# resends the user's username via email 
def resend_username(request):
    if request.method == 'POST':
        email = request.POST.get('email')

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            user = None
        
        if user:
            subject = 'Your Username - Intelligent Q&A Forums'
            email_to = [user.email] 
            with open(settings.BASE_DIR + "/main/templates/main/authentication/forgot-username/resend_username_email.txt") as temp:
                resend_username_email = temp.read()
            email = EmailMultiAlternatives(
                subject=subject, 
                body=resend_username_email,
                from_email=settings.EMAIL_HOST_USER,
                to=email_to
            )
            html = get_template("main/authentication/forgot-username/resend_username_email.html").render({'user': user})
            email.attach_alternative(html, "text/html")
            email.send()

        return render(request, 'main/authentication/login.html', {'activation_success': 'If your email address is linked with an account, an email will be sent to you with your username.'})

    else:
        return render(request, 'main/authentication/forgot-username/resend-username.html', {})

# send the user an email with a passcode to reset their password
def reset_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            user = None
        
        if user:
            userProfile = UserProfile.objects.get(user=user)
            # resetPasswordCode is a combination of 15 different letters/numbers 
            userProfile.resetPasswordCode = "".join(random.choices(string.ascii_uppercase + string.digits, k=15))
            userProfile.save() 
            
            # emailing the user with their resetPasswordCode
            subject = 'Reset your Password - Intelligent Q&A Forums'
            email_to = [userProfile.user.email] 
            with open(settings.BASE_DIR + "/main/templates/main/authentication/forgot-password/reset_password_email.txt") as temp:
                reset_password_email = temp.read()
            email = EmailMultiAlternatives(
                subject=subject, 
                body=reset_password_email,
                from_email=settings.EMAIL_HOST_USER,
                to=email_to
            )
            html = get_template("main/authentication/forgot-password/reset_password_email.html").render({'userProfile': userProfile})
            email.attach_alternative(html, "text/html")
            email.send()

        return render(request, 'main/authentication/forgot-password/reset-password-auth.html', {'reset_password_email_sent': 'If the email address is correct, a temp code will be sent to you.'})

    else:
        return render(request, 'main/authentication/forgot-password/reset-password.html', {})

# authenticating the user to reset their password  
def reset_password_auth(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        temp_code = request.POST.get('temp_code')
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            user = None 
        
        if user:
            userProfile = UserProfile.objects.get(user=user)

            if email == userProfile.user.email and temp_code == userProfile.resetPasswordCode: 
                userProfile.resetPasswordCode = "".join(random.choices(string.ascii_uppercase + string.digits, k=15)) # change resetPasswordCode for security reasons
                userProfile.save()
                return render(request, 'main/authentication/forgot-password/reset-password-confirm.html', {'reset_user_auth': 'Success! You can now reset your password!', 'user': user})
            else: 
                return render(request, 'main/authentication/forgot-password/reset-password-auth.html', {'error': 'Sorry, unable to reset your password'})

        else:
            return render(request, 'main/authentication/forgot-password/reset-password-auth.html', {'error': 'Sorry, unable to reset your password'})
    else:

main/templates/main/flagged-posts/disable-comment.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'post-comment-reply/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

{% include "main/navigationbar.html" %}

<div class='wrapper'>
    <h1>Are you sure you want to {% if comment.commentDisabled %}enable{% else %}disable{% endif %} this comment?</h1>
    <div class='post-title'>
        <h2 style='word-break: break-all;'>{{comment.commentContent}}</h2>
        <p class='discussion-postedBy-and-date'>By: {{comment.commentBy}} on {{comment.commentDate}}</p>
    </div>

    <a class='button blue' href="{% url 'main:flagged-posts' %}">Back</a>
    <a class='button blue' href="{% url 'comment:disable-comment-confirm' comment.pk %}">{% if comment.commentDisabled %}Enable{% else %}Disable{% endif %}</a>

</div>

main/templates/main/flagged-posts/disable-post.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'post-comment-reply/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

{% include "main/navigationbar.html" %}

<div class='wrapper'>
    <h1>Are you sure you want to {% if post.postDisabled %}enable{% else %}disable{% endif %} this post?</h1>
    <div class='post-title'>
        <h2 style='word-break: break-all;'>{{post.postTitle}}</h2>
        <p class='discussion-postedBy-and-date'>By: {{post.postedBy}} on {{post.postDate}}</p>
    </div>

    <a class='button blue' href="{% url 'main:flagged-posts' %}">Back</a>
    <a class='button blue' href="{% url 'post:disable-post-confirm' post.pk %}">{% if post.postDisabled %}Enable{% else %}Disable{% endif %}</a>

</div>

main/templates/main/flagged-posts/disable-reply.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'post-comment-reply/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

{% include "main/navigationbar.html" %}

<div class='wrapper'>
    <h1>Are you sure you want to {% if reply.replyDisabled %}enable{% else %}disable{% endif %} this reply?</h1>
    <div class='post-title'>
        <h2 style='word-break: break-all;'>{{reply.replyContent}}</h2>
        <p class='discussion-postedBy-and-date'>By: {{reply.replyBy}} on {{reply.replyDate}}</p>
    </div>

    <a class='button blue' href="{% url 'main:flagged-posts' %}">Back</a>
    <a class='button blue' href="{% url 'reply:disable-reply-confirm' reply.pk %}">{% if reply.replyDisabled %}Enable{% else %}Disable{% endif %}</a>

</div>

main/templates/main/flagged-posts/flagged-posts.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'allPosts/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

{% include "main/navigationbar.html" %}

<div class='wrapper'>
    {% if flagged.posts or flagged.comments or flagged.replies %}
        <h1>Flagged Posts:</h1>
        <table class="postsTable">
            <tr>
                <th width="22%">Post</th>
                <th width="23%">Posted By</th>
                <th width="10%">Flags</th>
                <th width="15%">Type</th>
                <th width="30%">Action</th>
            </tr>
    {% endif %}
    {% comment %} FLAGGED POSTS {% endcomment %}
    {% if flagged.posts %}
        {% for post in flagged.posts %}
            <tr {% if post.postDisabled %}class='disabled'{% endif %}>
                <td><a style='word-break: break-all' href="{% url 'post:show-post' post.id %}">{{post.postTitle}}</a>{% if post.postDisabled %}<strong><i> - Currently Disabled (Not shown in the forums)</i></strong>{% endif %}</td>
                <td><a href="{% url 'main:profile' post.postedBy %}" >{{post.postedBy.user.first_name}} {{post.postedBy.user.last_name}}</a></td>
                <td>{{post.postFlags.count}}&nbsp;&nbsp;<i class="fas fa-flag"></i></td>
                <td>Post</td>
                <td align='center' class='flagged-posts-buttons'>
                    <div class='buttons-div'>
                        <div class='button-div'>
                            <a href="{% url 'post:delete-post' post.pk %}" style='background:#21618C' name='delete-button'><i class="fas fa-trash-alt"></i></a>
                            <span>Delete</span>
                        </div>
                        <div class='button-div'>
                            {% if post.postDisabled %}
                                <a href="{% url 'post:disable-post' post.pk %}" style='background:green' name='enable-button'><i class="far fa-check-circle"></i></a>
                                <span>Enable </span>
                            {% else %}
                                <a href="{% url 'post:disable-post' post.pk %}" style='background:#CB4335' name='disable-button'><i class="fas fa-ban"></i></a>
                                <span>Disable </span>
                            {% endif %}
                        </div>
                        <div class='button-div'>
                            <a href="{% url 'post:remove-post-flags' post.pk %}"  style='background:#DC7633' name='flags-button'><i class="fas fa-flag"></i></a>
                            <span>Remove Flags</span>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    {% endif %}
    {% comment %} FLAGGED COMMENTS {% endcomment %}
    {% if flagged.comments %}
        {% for comment in flagged.comments %}
            <tr {% if comment.commentDisabled %}class='disabled'{% endif %}>
                <td><a style='word-break: break-all' href="{% url 'post:show-post' comment.commentOnPost.pk %}">{{comment.commentContent}}</a>{% if comment.commentDisabled %}<strong><i> - Currently Disabled (Not shown in the forums)</i></strong>{% endif %}</td>
                <td><a href="{% url 'main:profile' comment.commentBy %}" >{{comment.commentBy.user.first_name}} {{comment.commentBy.user.last_name}}</a></td>
                <td>{{comment.commentFlags.count}}&nbsp;&nbsp;<i class="fas fa-flag"></i></td>
                <td>Comment</td>
                <td align='center' class='flagged-posts-buttons'>
                    <div class='buttons-div'>
                        <div class='button-div'>
                            <a href="{% url 'comment:delete-comment' comment.commentOnPost.pk comment.pk %}" style='background:#21618C'><i class="fas fa-trash-alt"></i></a>
                            <span>Delete</span>
                        </div>
                        <div class='button-div'>
                            {% if comment.commentDisabled %}
                                <a href="{% url 'comment:disable-comment' comment.pk %}" style='background:green'><i class="far fa-check-circle"></i></a>
                                <span>Enable</span>
                            {% else %}
                                <a href="{% url 'comment:disable-comment' comment.pk %}" style='background:#CB4335'><i class="fas fa-ban"></i></a>
                                <span>Disable</span>
                            {% endif %}
                        </div>
                        <div class='button-div'>
                            <a href="{% url 'comment:remove-comment-flags' comment.pk %}"  style='background:#DC7633'><i class="fas fa-flag"></i></a>
                            <span>Remove Flags</span>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    {% endif %}
    {% comment %} FLAGGED REPLIES {% endcomment %}
    {% if flagged.replies %}
        {% for reply in flagged.replies %}
            <tr {% if reply.replyDisabled %}class='disabled'{% endif %}>
                <td><a style='word-break: break-all' href="{% url 'post:show-post' reply.replytoComment.commentOnPost.pk %}">{{reply.replyContent}}</a>{% if reply.replyDisabled %}<strong><i> - Currently Disabled (Not shown in the forums)</i></strong>{% endif %}</td>
                <td><a href="{% url 'main:profile' reply.replyBy %}" >{{reply.replyBy.user.first_name}} {{reply.replyBy.user.last_name}}</a></td>
                <td>{{reply.replyFlags.count}}&nbsp;&nbsp;<i class="fas fa-flag"></i></td>
                <td>Reply</td>
                <td align='center' class='flagged-posts-buttons'>
                    <div class='buttons-div'>
                        <div class='button-div'>
                            <a href="{% url 'reply:delete-reply' reply.replytoComment.commentOnPost.pk reply.pk %}" style='background:#21618C'><i class="fas fa-trash-alt"></i></a>
                            <span>Delete </span>
                        </div>
                        <div class='button-div'>
                            {% if reply.replyDisabled %}
                                <span>Enable</span><a href="{% url 'reply:disable-reply' reply.pk %}" style='background:green'><i class="far fa-check-circle"></i></a>
                            {% else %}
                                <span>Disable</span><a href="{% url 'reply:disable-reply' reply.pk %}" style='background:#CB4335'><i class="fas fa-ban"></i></a>
                            {% endif %}
                        </div>
                        <div class='button-div'>
                            <a href="{% url 'reply:remove-reply-flags' reply.pk %}"  style='background:#DC7633'><i class="fas fa-flag"></i></a>
                            <span>Remove Flags</span>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    {% endif %}

    {% if flagged.posts or flagged.comments or flagged.replies %}
        </table>
    {% else %}
        <h1>Great News! There are no flagged posts.</h1>
    {% endif %}
</div>

<script type='text/javascript' src="{% static 'allPosts/post.js' %}"></script>