comment/urls.py
from django.conf.urls import url
from . import views

app_name = 'comment'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^(?P<pk>[0-9]+)/add-comment/$', views.Comment_Create.as_view(), name='add-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/edit-comment/$', views.Comment_Update.as_view(), name='edit-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/delete-comment/$', views.Comment_Delete.as_view(), name='delete-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/comment-like/$', views.Comment_Like.as_view(), name='like-comment'),
    url(r'^(?P<pk>[0-9]+)/comment-likes-list/$', views.Comment_Likes_List.as_view(), name='like-list-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/comment-vote-up/$', views.Comment_Vote_Up.as_view(), name='vote-up-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/comment-vote-down/$', views.Comment_Vote_Down.as_view(), name='vote-down-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/report-comment/$', views.Comment_Report.as_view(), name='report-comment'),
    url(r'^(?P<pk>[0-9]+)/disable-comment/$', views.Comment_Enable_Disable_Page.as_view(), name='disable-comment'),
    url(r'^(?P<pk>[0-9]+)/disable-comment-confirm/$', views.Comment_Enable_Disable.as_view(), name='disable-comment-confirm'),
    url(r'^(?P<pk>[0-9]+)/remove-comment-flags/$', views.Comment_Remove_Flags_Page.as_view(), name='remove-comment-flags'),
    url(r'^(?P<pk>[0-9]+)/remove-comment-flags-confirm/$', views.Comment_Remove_Flags.as_view(), name='remove-comment-flags-confirm'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/accept-answer/$', views.Accept_Answer.as_view(), name='accept-answer'),
]

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='user-login'),
    url(r'^logout/$', views.user_logout, name='user-logout'),
    url(r'^activate/$', views.activate, name='activate'),
    url(r'^resend-username/$', views.resend_username, name='resend-username'),
    url(r'^reset-password/$', views.reset_password, name='reset-password'),
    url(r'^reset-password-auth/$', views.reset_password_auth, name='reset-password-auth'),
    url(r'^reset-password-confirm/$', views.reset_password_confirm, name='reset-password-confirm'),
    url(r'^profile/(?P<user>[A-Za-z0-9]+)$', views.profile_info, name='profile'),    
    url(r'^edit-profile/(?P<user>[A-Za-z0-9]+)$', views.edit_profile_info, name='edit-profile'),    
    url(r'^delete-profile/$', views.delete_profile_and_user, name='delete-profile'),    
    url(r'^delete-profile-confirm/$', views.delete_profile_and_user_confirm, name='delete-profile-confirm'),    
    url(r'^flagged-posts/$', views.flagged_posts_view, name='flagged-posts'),    
    url(r'^staff/$', views.staff, name='staff'), 
    url(r'^update-staff/(?P<user>[A-Za-z0-9]+)', views.update_staff_status, name='update-staff'),
    url(r'^update-active/(?P<user>[A-Za-z0-9]+)', views.update_active_status, name='update-active'),

    # URL links for class-based views 
    url(r'^$', views.Index_View.as_view(), name='index'),
    url(r'^topics/$', views.Topics_View.as_view(), name='topics'),
    url(r'^topics/(?P<topic>[A-Za-z0-9]+)', views.Posts_With_Same_Topic_View.as_view(), name='topic'),
    
    url(r'^page-not-found/', views.pageNotFound, name='page-not-found'), 

]

post/urls.py
from django.conf.urls import url
from . import views
# from django.contrib.admin.views.decorators import staff_member_required

app_name = 'post'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^(?P<pk>[0-9]+)/$', views.Show_Post_View.as_view(), name='show-post'),
    url(r'^add-post/$', views.Post_Create.as_view(), name='add-post'),
    url(r'^(?P<pk>[0-9]+)/edit-post/$', views.Post_Update.as_view(), name='edit-post'),
    url(r'^(?P<pk>[0-9]+)/delete-post/$', views.Post_Delete.as_view(), name='delete-post'),
    url(r'^(?P<pk>[0-9]+)/like/$', views.Post_Like.as_view(), name='like-post'),
    url(r'^(?P<pk>[0-9]+)/post-likes-list/$', views.Post_Likes_List.as_view(), name='like-list-post'),
    url(r'^(?P<pk>[0-9]+)/post-vote-up/$', views.Post_Vote_Up.as_view(), name='vote-up-post'),
    url(r'^(?P<pk>[0-9]+)/post-vote-down/$', views.Post_Vote_Down.as_view(), name='vote-down-post'),
    url(r'^(?P<pk>[0-9]+)/report-post/$', views.Post_Report.as_view(), name='report-post'),
    url(r'^(?P<pk>[0-9]+)/disable-post/$', views.Post_Enable_Disable_Page.as_view(), name='disable-post'),
    url(r'^(?P<pk>[0-9]+)/disable-post-confirm/$', views.Post_Enable_Disable.as_view(), name='disable-post-confirm'),
    url(r'^(?P<pk>[0-9]+)/remove-post-flags/$', views.Post_Remove_Flags_Page.as_view(), name='remove-post-flags'),
    url(r'^(?P<pk>[0-9]+)/remove-post-flags-confirm/$', views.Post_Remove_Flags.as_view(), name='remove-post-flags-confirm'),
    url(r'^(?P<pk>[0-9]+)/open-comments/$', views.Post_Open_Comments.as_view(), name='open-comments'),
]

reply/urls.py
from django.conf.urls import url
from . import views

app_name = 'reply'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^(?P<post_pk>[0-9]+)/(?P<comment_pk>[0-9]+)/add-reply/$', views.Reply_Create.as_view(), name='add-reply'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/edit-reply/$', views.Reply_Update.as_view(), name='edit-reply'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/delete-reply/$', views.Reply_Delete.as_view(), name='delete-reply'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/reply-like/$', views.Reply_Like.as_view(), name='like-reply'),
    url(r'^(?P<pk>[0-9]+)/reply-likes-list/$', views.Reply_Likes_List.as_view(), name='like-list-reply'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/report-reply/$', views.Reply_Report.as_view(), name='report-reply'),
    url(r'^(?P<pk>[0-9]+)/disable-reply/$', views.Reply_Enable_Disable_Page.as_view(), name='disable-reply'),
    url(r'^(?P<pk>[0-9]+)/disable-reply-confirm/$', views.Reply_Enable_Disable.as_view(), name='disable-reply-confirm'),
    url(r'^(?P<pk>[0-9]+)/remove-reply-flags/$', views.Reply_Remove_Flags_Page.as_view(), name='remove-reply-flags'),
    url(r'^(?P<pk>[0-9]+)/remove-reply-flags-confirm/$', views.Reply_Remove_Flags.as_view(), name='remove-reply-flags-confirm'),
    
]

comment/models.py
from django.db import models
from post.models import Post
from main.models import UserProfile

# a model for storing a comment in the database 
class Comment(models.Model):
    commentOnPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentContent = models.TextField(max_length=350, verbose_name=('Comment on Post:'))
    commentBy = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    commentImage = models.ImageField(null=True, blank=True)
    commentDate = models.DateTimeField(auto_now=False, auto_now_add=True)
    commentLikes = models.ManyToManyField(UserProfile, blank=True, related_name='comment_likes')
    commentNumberOfVotes = models.IntegerField(default=0)
    commentVotersUp = models.ManyToManyField(UserProfile, blank=True, related_name='comment_votes_up')
    commentVotersDown = models.ManyToManyField(UserProfile, blank=True, related_name='comment_votes_down')
    commentFlags = models.ManyToManyField(UserProfile, blank=True, related_name='comment_flags')
    commentDisabled = models.BooleanField(default=False)
    commentAccepted = models.BooleanField(default=False)

    # a string representation of the object stored 
    def __str__(self):
        return "Comment " + str(self.pk) + " on " + str(self.commentOnPost)

    # list comments in a descending order according to the number of votes
    class Meta:
        ordering=["-commentNumberOfVotes"]

post/models.py
from django.db import models
from django.urls import reverse
from main.models import UserProfile

# a model for storing a post in the database 
class Post(models.Model):
    postedBy = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    postTitle = models.CharField(max_length=80, verbose_name=('Post Title'))
    postTopic = models.CharField(max_length=60, verbose_name=('Post Topic'), blank=True)
    postTopicRelatedWords = models.TextField(max_length=150, blank=True)
    postContent = models.TextField(max_length=350, verbose_name=('Post'))
    postImage = models.ImageField(null=True, blank=True)
    postLastUpdated = models.DateTimeField(auto_now=True, auto_now_add=False)
    postDate = models.DateTimeField(auto_now=False, auto_now_add=True)
    postLikes = models.ManyToManyField(UserProfile, blank=True, related_name='post_likes')
    postNumberOfVotes = models.IntegerField(default=0)
    postVotersUp = models.ManyToManyField(UserProfile, blank=True, related_name='post_votes_up')
    postVotersDown = models.ManyToManyField(UserProfile, blank=True, related_name='post_votes_down')
    postNumberOfComments = models.IntegerField(default=0)
    postFlags = models.ManyToManyField(UserProfile, blank=True, related_name='post_flags')
    postDisabled = models.BooleanField(default=False)
    postClosed = models.BooleanField(default=False)
    postAutoClassification = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("post:show-post", kwargs={"pk": self.pk})
    
    # a string representation of the object stored 
    def __str__(self):
        return "Post " + str(self.pk) 
    
    # list posts in a descending order according to the number of votes then the post date 
    class Meta:
        ordering=["-postNumberOfVotes", "-postDate"]

reply/models.py
from django.db import models
from main.models import UserProfile
from comment.models import Comment

# a model for storing a reply in the database 
class Reply(models.Model):
    replytoComment = models.ForeignKey(Comment ,on_delete=models.CASCADE)
    replyContent = models.TextField(max_length=350, verbose_name=('Reply to Comment:'))
    replyBy = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    replyDate = models.DateTimeField(auto_now=False, auto_now_add=True)
    replyLikes = models.ManyToManyField(UserProfile, blank=True, related_name='reply_likes')
    replyFlags = models.ManyToManyField(UserProfile, blank=True, related_name='reply_flags')
    replyDisabled = models.BooleanField(default=False)

    # a string representation of the object stored 
    def __str__(self):
        return "Reply " + str(self.pk) + " to " + str(self.replytoComment)
    

post/forms.py
from django import forms
from django.contrib.auth.models import User
from post.models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User 
        fields = ('first_name', 'last_name', 'username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfile 
        fields = ('profile_picture',)

post/templates/post/comment.html
<table class='comment card '>
    <td class='vote-up-and-down'>
        {% if user in comment.commentVotersUp.all  %}
            <a href="{% url 'post:vote-up-comment' post.pk comment.pk %}" style='color:green'><i class="fas fa-angle-up"></i></a>
        {% else %}
            <a href="{% url 'post:vote-up-comment' post.pk comment.pk %}"><i class="fas fa-angle-up"></i></a>
        {% endif %}
        
        <p>{{comment.commentNumberOfVotes}}</p>
        
        {% if user in comment.commentVotersDown.all  %}
            <a href="{% url 'post:vote-down-comment' post.pk comment.pk %}" style='color:#CB4335'><i class="fas fa-angle-down"></i></a>
        {% else %}
            <a href="{% url 'post:vote-down-comment' post.pk comment.pk %}"><i class="fas fa-angle-down"></i></a>
        {% endif %}
    
    </td>

    {% include "post/widgets/name-photo-card.html" with author=comment.commentBy %}

    <td class='post-content'>
        <p>{{comment.commentContent}}</p>

        {% if user.is_authenticated %}
            {% if user.username == comment.commentBy.username or user.is_superuser %}
                {% url 'post:edit-comment' post.pk comment.pk as the_edit_url %}
                {% url 'post:delete-comment' post.pk comment.pk as the_delete_url %}
                {% include "post/widgets/edit-delete-dropdown.html" with edit_url=the_edit_url delete_url=the_delete_url %}
            {% endif %}
        {% endif %}

        <div class='buttons-and-date-fixed-bottom'>
            <p style='margin-bottom: -5px; padding: 0;'>{{comment.commentLikes.count}} Like{% if comment.commentLikes.count > 1 or comment.commentLikes.count == 0 %}s{% endif %}
            {% if comment.commentLikes.count > 2 and user in comment.commentLikes.all %}
                (You and {{comment.commentLikes.count|add:'-1'}} others).</p>
            {% elif comment.commentLikes.count > 1 and user in comment.commentLikes.all  %}
                (You and {{comment.commentLikes.count|add:'-1'}} other).</p>
            {% elif comment.commentLikes.count == 1 and user in comment.commentLikes.all %}
                (You).
            {% endif %}
            <hr/>

            {% if user.is_authenticated %}
                {% comment %} <button class='button blue'>Like <i class="far fa-thumbs-up"></i></button> {% endcomment %}
                {% comment %} <a class='button blue' href='{{comment.pk}}/like/'>Like <i class="far fa-thumbs-up"></i></a> {% endcomment %}
                {% if user in comment.commentLikes.all %}
                    <a class='comment-link' style='background:green' href='{{comment.pk}}/comment-like/'>Like <i class="fas fa-thumbs-up"></i></a>
                {% else %}
                    <a class='comment-link' href='{{comment.pk}}/comment-like/'>Like <i class="far fa-thumbs-up"></i></a>
                {% endif %}
                <a class='button blue' href='{{comment.pk}}/add-reply/'>Reply <i class="fas fa-reply"></i></a>
                <button class='button danger' onclick="report('comment', {{comment.pk}})">Report <i class="fas fa-ban"></i></button>
                {% if user in comment.commentFlags.all %}<span style='color:#CB4335'><strong><i>- You have reported this comment.</i></strong></span>{% endif %}
            {% else %}
                <p>To reply to a comment, you must be logged in. <a class='button blue' href="{% url 'post:user_login' %}">Click here to Login</a></p>
            {% endif %}
            <p>{{comment.commentDate}}</p>
        </div>
    </td>
</table>

post/templates/post/navigationbar.html
{% load staticfiles %}
{% comment %} <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" /> {% endcomment %}
<link rel="stylesheet" type="text/css" href="{% static 'navigationbar/style.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">

<div class="navigationbar">
    <button class='logo'>Intelligent Q&#38;A Forums</button>
    <a href="{% url 'post:index'%}">All Posts</a>
    <a href="{% url 'post:topics'%}">Topics</a>
    {% if user.is_authenticated %}
        <a href="{% url 'post:add-post'%}"><i class="fas fa-plus"></i>&nbsp; Add New Post</a>
    {% endif %}
    {% if user.is_superuser %}
        <a href="{% url 'post:flagged-posts'%}"><i class="fas fa-exclamation-circle"></i>&nbsp; Flagged Posts</a>
    {% endif %}
    <a style="float:right" href="/admin"><i class="fas fa-unlock-alt"></i>&nbsp; Admin</a>

    {% if user.is_authenticated %}
        <div style="float:right" class="dropdown">
            <button class="dropbtn">
            {% if user.first_name %}
                Hey, <strong>{{user.first_name}}</strong>!&nbsp; 
            {% else %}
                Hey, <strong>{{user.username}}</strong>!&nbsp; 
            {% endif %}
            <i class="fa fa-caret-down"></i></button>
            <div class="dropdown-content">
                <a href="{% url 'post:profile' user %}"><i class="fas fa-user"></i>&nbsp; My Profile</a>
                <a href="{% url 'post:logout' %}"><i class="fas fa-sign-out-alt"></i>&nbsp; Logout</a>
            </div>
        </div> 
        {% comment %} <li style="float:right"><a href="{% url 'post:logout' %}"><i class="fas fa-sign-out-alt"></i>&nbsp; Logout</a></li> {% endcomment %}
    {% else %}
        <a style="float:right" href="{% url 'post:register' %}"><i class="fas fa-user-plus"></i>&nbsp; Sign Up</a>
        <a style="float:right" href="{% url 'post:user_login' %}"><i class="fas fa-sign-in-alt"></i>&nbsp; Login</a>
    {% endif %}

</div>

post/templates/post/post-comment-reply.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'post-comment-reply/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

{% include "main/navigationbar.html" %}

<div class='post-topic'>
    <h3 style='word-break: break-all'>
        <a href="{% url 'main:topic' postTopicNoSpaces %}">
            {{post.postTopic}}{% if post.postAutoClassification == True %} - (Automatically Classified){% endif %}
        </a>
    </h3>
    {% if post.postTopicRelatedWords %}
        <p style='margin-bottom:0; padding: 0px 10px; color:gray;'>Words that appear frequently in this topic according to our dataset:</p>
        <h4 style='margin-top:0; padding: 0px 10px; color:gray;'>{{post.postTopicRelatedWords}}</h4>
    {% endif %}
</div>

{% if post.postDisabled %}
    <div class='post-disabled-message'>This post is currently disabled and is not accessible to basic-type users. Only Staff members can view it.</div>
{% endif %}

<div class='wrapper'>
    <div class='post-title'>
        {% if user.is_authenticated %}
            {% if user.username == post.postedBy.user.username and post.postClosed == True %}
                <a class='button green repoen-comments-button' href="{% url 'post:open-comments' post.pk %}">Re-open Post Comments</a>
            {% endif %}
        {% endif %}
        <h1 style='width: 75%; word-break: break-all'>{{post.postTitle}}</h1>
        {% if post.postClosed %}
            <h2 style='color:#CB4335;'>[CLOSED. Author has accepted one of the answers]</h2>
        {% endif %}
        <p class='discussion-postedBy-and-date'>Discussion started by: 
            <a class='discussion-started-by' href="{% url 'main:profile' post.postedBy.user %}" >
                {{post.postedBy.user.first_name}} {{post.postedBy.user.last_name}}
            </a> on {{post.postDate}}
            {% if post.postLastUpdated > post.postDate %} - latest update on {{post.postLastUpdated}}{% endif %}
        </p>
    </div>
    <hr />

    {% include "post/post.html" %}
    
    {% if post.comment_set.all %}
        {% comment %} show the accepted comment first {% endcomment %}
        {% for comment in post.comment_set.all %}
            {% if comment.commentAccepted and not comment.commentDisabled %} 
                {% include "comment/comment.html" %}
                {% for reply in comment.reply_set.all %}
                    {% if not reply.replyDisabled %}
                        {% include "reply/reply.html" %}
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endfor %}
        
        {% comment %} show all the other comments {% endcomment %}
        {% for comment in post.comment_set.all %}
            {% if not comment.commentAccepted and not comment.commentDisabled %}
                {% include "comment/comment.html" %}
                {% for reply in comment.reply_set.all %}
                    {% if not reply.replyDisabled %}
                        {% include "reply/reply.html" %}
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% else %}
        <div style='padding: 10px 3%; width:94%; border:1px solid gray;'>
            <p>No Comments yet.</p>
        </div>
    {% endif %}
    
</div>

post/templates/post/post.html
{% load staticfiles %}
<table class='post card'>
    <td class='vote-up-and-down'>
        {% if user.is_authenticated %}
            {% if logged_in_user_profile in post.postVotersUp.all  %}
                <a name='vote-up-post' href="{% url 'post:vote-up-post' post.pk %}" style='color:green'><i class="fas fa-angle-up"></i></a>
            {% else %}
                <a name='vote-up-post' href="{% url 'post:vote-up-post' post.pk %}"><i class="fas fa-angle-up"></i></a>
            {% endif %}
            
            <p name='postNumberOfVotes'>{{post.postNumberOfVotes}}</p>
            
            {% if logged_in_user_profile in post.postVotersDown.all  %}
                <a name='vote-down-post' href="{% url 'post:vote-down-post' post.pk %}" style='color:#CB4335'><i class="fas fa-angle-down"></i></a>
            {% else %}
                <a name='vote-down-post' href="{% url 'post:vote-down-post' post.pk %}"><i class="fas fa-angle-down"></i></a>
            {% endif %}
        {% else %}
            <p>{{post.postNumberOfVotes}}</p>
        {% endif %}
    </td>
    
    {% include "main/widgets/name-photo-card.html" with user_profile=post.postedBy %}

    <td class='post-content'>
        <p class= 'post-content-text' style='word-break: break-all;'>{{post.postContent}}</p>

        {% if post.postImage %}
            <div class='postImageContainer' onmouseover='fadeOutDateAndButtons()' onmouseout='fadeInDateAndButtons()'>
                <img class='postImage' src='{{ post.postImage.url }}' />   
            </div>
        {% endif %}

        {% if user.is_authenticated %}
            {% if user.username == post.postedBy.user.username %}
                {% url 'post:edit-post' post.pk as the_edit_url %}
                {% url 'post:delete-post' post.pk as the_delete_url %}
                {% include "main/widgets/edit-delete-dropdown.html" with edit_url=the_edit_url delete_url=the_delete_url type="post-ellipsis" %}
            {% endif %}
        {% endif %}
        
        <div class='buttons-and-date-fixed-bottom'>
            <a href="{% url 'post:like-list-post' post.pk %}" name='post-likes' class='likes'>{{post.postLikes.count}} Like{% if post.postLikes.count > 1 or post.postLikes.count == 0 %}s{% endif %}
                {% if post.postLikes.count > 2 and logged_in_user_profile in post.postLikes.all %}
                    (You and {{post.postLikes.count|add:'-1'}} others).
                {% elif post.postLikes.count > 1 and logged_in_user_profile in post.postLikes.all  %}
                    (You and {{post.postLikes.count|add:'-1'}} other).
                {% elif post.postLikes.count == 1 and logged_in_user_profile in post.postLikes.all %}
                    (You).
                {% endif %}
            </a>
            <hr/>
            {% if user.is_authenticated %}
                {% if logged_in_user_profile in post.postLikes.all %}
                    <span class='link-spaces'><a class='comment-link' style='background:green' name='post-like-button' href='like/'>Like <i class="fas fa-thumbs-up"></i></a></span>
                {% else %}
                    <span class='link-spaces'><a class='comment-link' name='post-like-button' href='like/'>Like <i class="far fa-thumbs-up"></i></a></span>
                {% endif %}
                {% if post.postClosed == False %}
                    <span class='link-spaces'><a class='comment-link' href='add-comment/'>Comment <i class="far fa-comment"></i></a></span>
                {% endif %}
                <span class='button-spaces'><button name='report-post' class='button danger' onclick="report('post', {{post.pk}})">Report <i class="fas fa-ban"></i></button></span>
                {% if logged_in_user_profile in post.postFlags.all %}<p style='color:#CB4335' name='reported-post'><strong><i>- You have reported this post.</i></strong></p>{% endif %}
            {% else %}
                <p>To comment on a question, you must be logged in.</p><p><a class='button blue' href="{% url 'main:user-login' %}?next={{post.pk}}">Click here to Login</a></p>
            {% endif %}
            <p>{{post.postDate}}</p>
        </div>
    </td>
</table>

<script type='text/javascript' src="{% static 'allPosts/post.js' %}"></script>

post/templates/post/reply.html
<table class='reply card '>

    {% include "post/widgets/name-photo-card.html" with author=reply.replyBy %}

    <td class='post-content'>
        <p>{{reply.replyContent}}</p>

        {% if user.is_authenticated %}
            {% if user.username == reply.replyBy.username or user.is_superuser %}
                {% url 'post:edit-reply' post.pk reply.pk as the_edit_url %}
                {% url 'post:delete-reply' post.pk reply.pk as the_delete_url %}
                {% include "post/widgets/edit-delete-dropdown.html" with edit_url=the_edit_url delete_url=the_delete_url %}
            {% endif %}
        {% endif %}

        <div class='buttons-and-date-fixed-bottom'>
            {% comment %} <p style='margin-bottom: -5px; padding: 0;'>{{reply.replyNumberOfreplyLikes}} replyLikes</p> {% endcomment %}
            <p style='margin-bottom: -5px; padding: 0;'>{{reply.replyLikes.count}} Like{% if reply.replyLikes.count > 1 or reply.replyLikes.count == 0 %}s{% endif %}
            {% if reply.replyLikes.count > 2 and user in reply.replyLikes.all %}
                (You and {{reply.replyLikes.count|add:'-1'}} others).</p>
            {% elif reply.replyLikes.count > 1 and user in reply.replyLikes.all  %}
                (You and {{reply.replyLikes.count|add:'-1'}} other).</p>
            {% elif reply.replyLikes.count == 1 and user in reply.replyLikes.all %}
                (You).
            {% endif %}
            <hr/>
            {% if user.is_authenticated %}
                {% if user in reply.replyLikes.all %}
                    <a class='comment-link' style='background:green' href='{{reply.pk}}/reply-like/'>Like <i class="fas fa-thumbs-up"></i></a>
                {% else %}
                    <a class='comment-link' href='{{reply.pk}}/reply-like/'>Like <i class="far fa-thumbs-up"></i></a>
                {% endif %}
                <button class='button danger' onclick="report('reply', {{reply.pk}})">Report <i class="fas fa-ban"></i></button>
                {% if user in reply.replyFlags.all %}<span style='color:#CB4335'><strong><i>- You have reported this reply.</i></strong></span>{% endif %}
            {% endif %}
            <p>{{reply.replyDate}}</p>
        </div>
    </td>
</table>