comment/urls.py
from django.conf.urls import url
from . import views

app_name = 'comment'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^(?P<pk>[0-9]+)/add-comment/$', views.Comment_Create.as_view(), name='add-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/edit-comment/$', views.Comment_Update.as_view(), name='edit-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/delete-comment/$', views.Comment_Delete.as_view(), name='delete-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/comment-like/$', views.Comment_Like.as_view(), name='like-comment'),
    url(r'^(?P<pk>[0-9]+)/comment-likes-list/$', views.Comment_Likes_List.as_view(), name='like-list-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/comment-vote-up/$', views.Comment_Vote_Up.as_view(), name='vote-up-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/comment-vote-down/$', views.Comment_Vote_Down.as_view(), name='vote-down-comment'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/report-comment/$', views.Comment_Report.as_view(), name='report-comment'),
    url(r'^(?P<pk>[0-9]+)/disable-comment/$', views.Comment_Enable_Disable_Page.as_view(), name='disable-comment'),
    url(r'^(?P<pk>[0-9]+)/disable-comment-confirm/$', views.Comment_Enable_Disable.as_view(), name='disable-comment-confirm'),
    url(r'^(?P<pk>[0-9]+)/remove-comment-flags/$', views.Comment_Remove_Flags_Page.as_view(), name='remove-comment-flags'),
    url(r'^(?P<pk>[0-9]+)/remove-comment-flags-confirm/$', views.Comment_Remove_Flags.as_view(), name='remove-comment-flags-confirm'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/accept-answer/$', views.Accept_Answer.as_view(), name='accept-answer'),
]

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='user-login'),
    url(r'^logout/$', views.user_logout, name='user-logout'),
    url(r'^activate/$', views.activate, name='activate'),
    url(r'^resend-username/$', views.resend_username, name='resend-username'),
    url(r'^reset-password/$', views.reset_password, name='reset-password'),
    url(r'^reset-password-auth/$', views.reset_password_auth, name='reset-password-auth'),
    url(r'^reset-password-confirm/$', views.reset_password_confirm, name='reset-password-confirm'),
    url(r'^profile/(?P<user>[A-Za-z0-9]+)$', views.profile_info, name='profile'),    
    url(r'^edit-profile/(?P<user>[A-Za-z0-9]+)$', views.edit_profile_info, name='edit-profile'),    
    url(r'^delete-profile/$', views.delete_profile_and_user, name='delete-profile'),    
    url(r'^delete-profile-confirm/$', views.delete_profile_and_user_confirm, name='delete-profile-confirm'),    
    url(r'^flagged-posts/$', views.flagged_posts_view, name='flagged-posts'),    
    url(r'^staff/$', views.staff, name='staff'), 
    url(r'^update-staff/(?P<user>[A-Za-z0-9]+)', views.update_staff_status, name='update-staff'),
    url(r'^update-active/(?P<user>[A-Za-z0-9]+)', views.update_active_status, name='update-active'),

    # URL links for class-based views 
    url(r'^$', views.Index_View.as_view(), name='index'),
    url(r'^topics/$', views.Topics_View.as_view(), name='topics'),
    url(r'^topics/(?P<topic>[A-Za-z0-9]+)', views.Posts_With_Same_Topic_View.as_view(), name='topic'),
    
    url(r'^page-not-found/', views.pageNotFound, name='page-not-found'), 

]

post/urls.py
from django.conf.urls import url
from . import views
# from django.contrib.admin.views.decorators import staff_member_required

app_name = 'post'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^(?P<pk>[0-9]+)/$', views.Show_Post_View.as_view(), name='show-post'),
    url(r'^add-post/$', views.Post_Create.as_view(), name='add-post'),
    url(r'^(?P<pk>[0-9]+)/edit-post/$', views.Post_Update.as_view(), name='edit-post'),
    url(r'^(?P<pk>[0-9]+)/delete-post/$', views.Post_Delete.as_view(), name='delete-post'),
    url(r'^(?P<pk>[0-9]+)/like/$', views.Post_Like.as_view(), name='like-post'),
    url(r'^(?P<pk>[0-9]+)/post-likes-list/$', views.Post_Likes_List.as_view(), name='like-list-post'),
    url(r'^(?P<pk>[0-9]+)/post-vote-up/$', views.Post_Vote_Up.as_view(), name='vote-up-post'),
    url(r'^(?P<pk>[0-9]+)/post-vote-down/$', views.Post_Vote_Down.as_view(), name='vote-down-post'),
    url(r'^(?P<pk>[0-9]+)/report-post/$', views.Post_Report.as_view(), name='report-post'),
    url(r'^(?P<pk>[0-9]+)/disable-post/$', views.Post_Enable_Disable_Page.as_view(), name='disable-post'),
    url(r'^(?P<pk>[0-9]+)/disable-post-confirm/$', views.Post_Enable_Disable.as_view(), name='disable-post-confirm'),
    url(r'^(?P<pk>[0-9]+)/remove-post-flags/$', views.Post_Remove_Flags_Page.as_view(), name='remove-post-flags'),
    url(r'^(?P<pk>[0-9]+)/remove-post-flags-confirm/$', views.Post_Remove_Flags.as_view(), name='remove-post-flags-confirm'),
    url(r'^(?P<pk>[0-9]+)/open-comments/$', views.Post_Open_Comments.as_view(), name='open-comments'),
]

qa_forums/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from main.views import pageNotFound
from django.conf.urls import handler404, handler500
from main import views

urlpatterns = [

    url(r'^admin/', admin.site.urls),

    # include all the other URL files from the other apps 
    url(r'^', include('post.urls')),
    url(r'^', include('comment.urls')),
    url(r'^', include('reply.urls')),
    url(r'^', include('main.urls')),
    
    url(r'^page-not-found/', pageNotFound)
] 

# urls for any images uploaded by user
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# handling errors in urls
handler404 = views.error_404
handler500 = views.error_500

reply/urls.py
from django.conf.urls import url
from . import views

app_name = 'reply'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^(?P<post_pk>[0-9]+)/(?P<comment_pk>[0-9]+)/add-reply/$', views.Reply_Create.as_view(), name='add-reply'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/edit-reply/$', views.Reply_Update.as_view(), name='edit-reply'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/delete-reply/$', views.Reply_Delete.as_view(), name='delete-reply'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/reply-like/$', views.Reply_Like.as_view(), name='like-reply'),
    url(r'^(?P<pk>[0-9]+)/reply-likes-list/$', views.Reply_Likes_List.as_view(), name='like-list-reply'),
    url(r'^(?P<post_pk>[0-9]+)/(?P<pk>[0-9]+)/report-reply/$', views.Reply_Report.as_view(), name='report-reply'),
    url(r'^(?P<pk>[0-9]+)/disable-reply/$', views.Reply_Enable_Disable_Page.as_view(), name='disable-reply'),
    url(r'^(?P<pk>[0-9]+)/disable-reply-confirm/$', views.Reply_Enable_Disable.as_view(), name='disable-reply-confirm'),
    url(r'^(?P<pk>[0-9]+)/remove-reply-flags/$', views.Reply_Remove_Flags_Page.as_view(), name='remove-reply-flags'),
    url(r'^(?P<pk>[0-9]+)/remove-reply-flags-confirm/$', views.Reply_Remove_Flags.as_view(), name='remove-reply-flags-confirm'),
    
]

post/forms.py
from django import forms
from django.contrib.auth.models import User
from post.models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User 
        fields = ('first_name', 'last_name', 'username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfile 
        fields = ('profile_picture',)

post/views.py
from django.views import generic
from django.shortcuts import redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import RedirectView
from main.models import UserProfile, User
from .models import Post
from comment.models import Comment
from reply.models import Reply
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import render
from .nmf import classify_post_topics
from main.views import send_report_email_to_staff, send_report_email_to_author


# shows a post only if it's not disabled 
class Show_Post_View(generic.DetailView):
    model = Post 
    template_name = 'post/post-comment-reply.html'
    def get(self, request, *args, **kwargs):
        logged_in_user = self.request.user
        try:
            post = get_object_or_404(Post, id=self.kwargs.get('pk'))

            # only staff and admin can view disabled posts 
            if (post.postDisabled and not logged_in_user.is_staff):
                return HttpResponseRedirect("/page-not-found") 
                
        except Http404:
            return HttpResponseRedirect("/page-not-found") # post not available in database

        try:
            return super(Show_Post_View, self).get(request, *args, **kwargs)
        except Http404:
            return HttpResponseRedirect("/page-not-found")
    
    # context data needed for the template 
    def get_context_data(self, **kwargs):
        context = super(Show_Post_View, self).get_context_data(**kwargs)
        logged_in_user = self.request.user
        if logged_in_user.is_authenticated:
            logged_in_user_profile = get_object_or_404(UserProfile, user=logged_in_user)
            context['logged_in_user_profile'] = logged_in_user_profile
        context['postTopicNoSpaces'] = self.object.postTopic.replace(" ", "")
        return context

# creates a post and allows classification either automatically or manually 
class Post_Create(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Post 
    fields = ['postTitle', 'postTopic', 'postContent', 'postImage']

    # always runs before the form_valid function 
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        postTitle = self.request.POST.get('postTitle')
        postTopic = self.request.POST.get('postTopic')
        postContent = self.request.POST.get('postContent')
        checkbox  = self.request.POST.get('postAutoClassification')

        if (postTopic == "" and checkbox != "on"):
            form.add_error('postTopic', 'Error') # making the form invalid 
        if form.is_valid():
            return self.form_valid(form)
        else:
            messages.error(request, "Error: Either tick the checkbox to automatically classify "
                            + "the topic of the post, or manually fill out the 'Post Topic' field.")
            return render(request, "post/post_form.html", {'postTitle': postTitle, 'postContent': postContent})

    def form_valid(self, form):
        self.object = form.save(commit=False) # don't save it in the database yet
        logged_in_user = self.request.user
        user_profile = get_object_or_404(UserProfile, user=logged_in_user)
        user_profile.numOfPostsCommentsReplies = user_profile.numOfPostsCommentsReplies + 1
        self.object.postedBy = user_profile
        checkbox = self.request.POST.get('postAutoClassification')
        if (checkbox == "on"):
            self.object.postAutoClassification = True

            # the post to classify is the title plus the content to get as much info as possible 
            postToAutoClassify = str(self.object.postTitle) + " " + str(self.object.postContent)
            
            # calling the classifying algorithm 
            topic = classify_post_topics(postToAutoClassify)

            self.object.postTopic = topic.topicName
            self.object.postTopicRelatedWords = topic.topicWords

        if 'postImage' in self.request.POST:
            self.object.postImage = self.request.POST.get('postImage')

        user_profile.save()
        return super(Post_Create, self).form_valid(form)

# updates a post after authenticating the user 
class Post_Update(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Post 
    template_name = 'post/post_edit_form.html'
    fields = ['postTitle', 'postTopic', 'postTopicRelatedWords', 'postContent', 'postImage']
    def get(self, request, *args, **kwargs):
        try:
            post = get_object_or_404(Post, id=self.kwargs.get('pk'))
            if (self.request.user == post.postedBy.user):
                return super(Post_Update, self).get(request, *args, **kwargs)
            else:
                return HttpResponseRedirect("/page-not-found") # only author can edit
        except Http404:
            return HttpResponseRedirect("/page-not-found") # post not available in database
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'postImage' in request.FILES:
            self.object.postImage = request.FILES['postImage']
        return super().post(request, *args, **kwargs)

# likes a post 
class Post_Like(LoginRequiredMixin, RedirectView):
    login_url = '/login/'
    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, id=self.kwargs.get('pk'))
        redirect_url = post.get_absolute_url()        
        logged_in_user = self.request.user
        user_profile = get_object_or_404(UserProfile, user=logged_in_user)
        if logged_in_user.is_authenticated:
            if user_profile in post.postLikes.all():
                post.postLikes.remove(user_profile)
                user_profile.numberOfLikes = user_profile.numberOfLikes - 1
            else:
                post.postLikes.add(user_profile)
                user_profile.numberOfLikes = user_profile.numberOfLikes + 1
        
        user_profile.save()
        return redirect_url

# shows a list of users who liked a post 
class Post_Likes_List(generic.DetailView):
    model = Post 
    template_name = 'post/post-likes-list.html'
    def get_context_data(self, **kwargs):
        post = Post.objects.get(id=self.kwargs['pk'])
        list_of_users = [] 
        for username in post.postLikes.all():
            user = get_object_or_404(User, username=username)
            list_of_users.append(user)
        return {'post': post, 'list_of_users': list_of_users}

# adds a vote up to the post 
class Post_Vote_Up(LoginRequiredMixin, RedirectView):
    login_url = '/login/'
    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, id=self.kwargs.get('pk'))
        redirect_url = post.get_absolute_url()
        logged_in_user = self.request.user 
        logged_in_user_profile = get_object_or_404(UserProfile, user=logged_in_user)

        if logged_in_user.is_authenticated:
            # if user has already voted down before pressing up, remove the vote down first 
            if logged_in_user_profile in post.postVotersDown.all():
                post.postVotersDown.remove(logged_in_user_profile)
                post.postNumberOfVotes = post.postNumberOfVotes + 1

            if logged_in_user_profile in post.postVotersUp.all():
                post.postVotersUp.remove(logged_in_user_profile)
                post.postNumberOfVotes = post.postNumberOfVotes - 1
            else:
                post.postVotersUp.add(logged_in_user_profile)
                post.postNumberOfVotes = post.postNumberOfVotes + 1
            post.save()
        return redirect_url

# adds a vote down to the post 
class Post_Vote_Down(LoginRequiredMixin, RedirectView):
    login_url = '/login/'
    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, id=self.kwargs.get('pk'))
        redirect_url = post.get_absolute_url()
        logged_in_user = self.request.user
        logged_in_user_profile = get_object_or_404(UserProfile, user=logged_in_user)

        if logged_in_user.is_authenticated:
             # if user has already voted up before pressing down, remove the vote up first 
            if logged_in_user_profile in post.postVotersUp.all():
                post.postVotersUp.remove(logged_in_user_profile)
                post.postNumberOfVotes = post.postNumberOfVotes - 1

            if logged_in_user_profile in post.postVotersDown.all():
                post.postVotersDown.remove(logged_in_user_profile)
                post.postNumberOfVotes = post.postNumberOfVotes + 1
                post.save()
            else:
                post.postVotersDown.add(logged_in_user_profile)
                post.postNumberOfVotes = post.postNumberOfVotes - 1
                post.save()
        return redirect_url

# deletes a post and all the comments and replies related 
class Post_Delete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Post 

    def get(self, request, *args, **kwargs):
        try:
            post = get_object_or_404(Post, id=self.kwargs.get('pk'))
            if (self.request.user == post.postedBy.user or self.request.user.is_staff):
                return super(Post_Delete, self).get(request, *args, **kwargs)
            else:
                return HttpResponseRedirect("/page-not-found") # only author or staff can delete
        except Http404:
            return HttpResponseRedirect("/page-not-found") # post not available in database

    def get_success_url(self):
        return reverse_lazy('main:index')

    # updating the likes counts and total number of posts for all users involved 
    def delete(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=self.kwargs.get('pk'))
        post_author_profile = post.postedBy

post/templates/post/flagged-posts/disable-comment.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'post-comment-reply/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

{% include "post/navigationbar.html" %}

<div class='wrapper'>
    <h1>Are you sure you want to {% if comment.commentDisabled %}enable{% else %}disable{% endif %} this comment?</h1>
    <div class='post-title'>
        <h2>{{comment.commentContent}}</h2>
        <p class='discussion-postedBy-and-date'>By: {{comment.commentBy}} on {{comment.commentDate}}</p>
    </div>

    <a class='button blue' href="{% url 'post:flagged-posts' %}">Back</a>
    <a class='button blue' href="{% url 'comment:disable-comment-confirm' comment.pk %}">{% if comment.commentDisabled %}Enable{% else %}Disable{% endif %}</a>

</div>

post/templates/post/flagged-posts/disable-post.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'post-comment-reply/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

{% include "post/navigationbar.html" %}

<div class='wrapper'>
    <h1>Are you sure you want to {% if post.postDisabled %}enable{% else %}disable{% endif %} this post?</h1>
    <div class='post-title'>
        <h2>{{post.postTitle}}</h2>
        <p class='discussion-postedBy-and-date'>By: {{post.postedBy}} on {{post.postDate}}</p>
    </div>

    <a class='button blue' href="{% url 'post:flagged-posts' %}">Back</a>
    <a class='button blue' href="{% url 'post:disable-post-confirm' post.pk %}">{% if post.postDisabled %}Enable{% else %}Disable{% endif %}</a>

</div>

post/templates/post/flagged-posts/flagged-posts.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'allPosts/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

{% include "post/navigationbar.html" %}

<div class='wrapper'>
    {% if flagged.posts or flagged.comments or flagged.replies %}
        <h1>Flagged Posts:</h1>
        <table class="postsTable">
            <tr>
                <th width="45%">Post</th>
                <th width="15%">Discussion Started By</th>
                <th width="10%">Number of Flags</th>
                <th width="10%">Type</th>
                <th>Action</th>
            </tr>
    {% endif %}
    {% if flagged.posts %}
        {% for post in flagged.posts %}
            <tr {% if post.postDisabled %}class='disabled'{% endif %}>
                <td><a href="{% url 'post:showPost' post.id %}">{{post.postTitle}}</a>{% if post.postDisabled %}<strong><i> - Currently Disabled (Not shown in the forums)</i></strong>{% endif %}</td>
                <td><a href="{% url 'post:profile' post.postedBy %}" >{{post.postedBy.first_name}} {{post.postedBy.last_name}}</a></td>
                <td>{{post.postFlags.count}}&nbsp;&nbsp;<i class="fas fa-flag"></i></td>
                <td>Post</td>
                <td align='center' class='flagged-posts-buttons'>
                    <div class='buttons-div'>
                        <div class='button-div'>
                            <a href="{% url 'post:delete-post' post.pk %}" style='background:#21618C'><i class="fas fa-trash-alt"></i></a>
                            <span>Delete</span>
                        </div>
                        <div class='button-div'>
                            {% if post.postDisabled %}
                                <a href="{% url 'post:disable-post' post.pk %}" style='background:green'><i class="far fa-check-circle"></i></a>
                                <span>Enable </span>
                            {% else %}
                                <a href="{% url 'post:disable-post' post.pk %}" style='background:#CB4335'><i class="fas fa-ban"></i></a>
                                <span>Disable </span>
                            {% endif %}
                        </div>
                        <div class='button-div'>
                            <a href="{% url 'post:remove-post-flags' post.pk %}"  style='background:#DC7633'><i class="fas fa-flag"></i></a>
                            <span>Remove Flags</span>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    {% endif %}

    {% if flagged.comments %}
        {% for comment in flagged.comments %}
            <tr {% if comment.commentDisabled %}class='disabled'{% endif %}>
                <td><a href="{% url 'post:showPost' comment.commentOnPost.pk %}">{{comment.commentContent}}</a>{% if comment.commentDisabled %}<strong><i> - Currently Disabled (Not shown in the forums)</i></strong>{% endif %}</td>
                <td><a href="{% url 'post:profile' comment.commentBy %}" >{{comment.commentBy.first_name}} {{comment.commentBy.last_name}}</a></td>
                <td>{{comment.commentFlags.count}}&nbsp;&nbsp;<i class="fas fa-flag"></i></td>
                <td>Comment</td>
                <td align='center' class='flagged-posts-buttons'>
                    <div class='buttons-div'>
                        <div class='button-div'>
                            <a href="{% url 'comment:delete-comment' comment.commentOnPost.pk comment.pk %}" style='background:#21618C'><i class="fas fa-trash-alt"></i></a>
                            <span>Delete</span>
                        </div>
                        <div class='button-div'>
                            {% if comment.commentDisabled %}
                                <a href="{% url 'comment:disable-comment' comment.pk %}" style='background:green'><i class="far fa-check-circle"></i></a>
                                <span>Enable</span>
                            {% else %}
                                <a href="{% url 'comment:disable-comment' comment.pk %}" style='background:#CB4335'><i class="fas fa-ban"></i></a>
                                <span>Disable</span>
                            {% endif %}
                        </div>
                        <div class='button-div'>
                            <a href="{% url 'comment:remove-comment-flags' comment.pk %}"  style='background:#DC7633'><i class="fas fa-flag"></i></a>
                            <span>Remove Flags</span>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    {% endif %}

    {% if flagged.replies %}
        {% for reply in flagged.replies %}
            <tr {% if reply.replyDisabled %}class='disabled'{% endif %}>
                <td><a href="{% url 'post:showPost' reply.replytoComment.commentOnPost.pk %}">{{reply.replyContent}}</a>{% if reply.replyDisabled %}<strong><i> - Currently Disabled (Not shown in the forums)</i></strong>{% endif %}</td>
                <td><a href="{% url 'post:profile' reply.replyBy %}" >{{reply.replyBy.first_name}} {{reply.replyBy.last_name}}</a></td>
                <td>{{reply.replyFlags.count}}&nbsp;&nbsp;<i class="fas fa-flag"></i></td>
                <td>Reply</td>
                <td align='center' class='flagged-posts-buttons'>
                    <div class='buttons-div'>
                        <div class='button-div'>
                            <a href="{% url 'reply:delete-reply' reply.replytoComment.commentOnPost.pk reply.pk %}" style='background:#21618C'><i class="fas fa-trash-alt"></i></a>
                            <span>Delete </span>
                        </div>
                        <div class='button-div'>
                            {% if reply.replyDisabled %}
                                <span>Enable</span><a href="{% url 'reply:disable-reply' reply.pk %}" style='background:green'><i class="far fa-check-circle"></i></a>
                            {% else %}
                                <span>Disable</span><a href="{% url 'reply:disable-reply' reply.pk %}" style='background:#CB4335'><i class="fas fa-ban"></i></a>
                            {% endif %}
                        </div>
                        <div class='button-div'>
                            <a href="{% url 'reply:remove-reply-flags' reply.pk %}"  style='background:#DC7633'><i class="fas fa-flag"></i></a>
                            <span>Remove Flags</span>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    {% endif %}

    {% if flagged.posts or flagged.comments or flagged.replies %}
        </table>
    {% else %}
        <h2>Great News! There are no flagged posts.</h2>
    {% endif %}
</div>

<script type='text/javascript' src="{% static 'allPosts/post.js' %}"></script>