main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='user-login'),
    url(r'^logout/$', views.user_logout, name='user-logout'),
    url(r'^activate/$', views.activate, name='activate'),
    url(r'^resend-username/$', views.resend_username, name='resend-username'),
    url(r'^reset-password/$', views.reset_password, name='reset-password'),
    url(r'^reset-password-auth/$', views.reset_password_auth, name='reset-password-auth'),
    url(r'^reset-password-confirm/$', views.reset_password_confirm, name='reset-password-confirm'),
    url(r'^profile/(?P<user>[A-Za-z0-9]+)$', views.profile_info, name='profile'),    
    url(r'^edit-profile/(?P<user>[A-Za-z0-9]+)$', views.edit_profile_info, name='edit-profile'),    
    url(r'^delete-profile/$', views.delete_profile_and_user, name='delete-profile'),    
    url(r'^delete-profile-confirm/$', views.delete_profile_and_user_confirm, name='delete-profile-confirm'),    
    url(r'^flagged-posts/$', views.flagged_posts_view, name='flagged-posts'),    
    url(r'^staff/$', views.staff, name='staff'), 
    url(r'^update-staff/(?P<user>[A-Za-z0-9]+)', views.update_staff_status, name='update-staff'),
    url(r'^update-active/(?P<user>[A-Za-z0-9]+)', views.update_active_status, name='update-active'),

    # URL links for class-based views 
    url(r'^$', views.Index_View.as_view(), name='index'),
    url(r'^topics/$', views.Topics_View.as_view(), name='topics'),
    url(r'^topics/(?P<topic>[A-Za-z0-9]+)', views.Posts_With_Same_Topic_View.as_view(), name='topic'),
    
    url(r'^page-not-found/', views.pageNotFound, name='page-not-found'), 

]

post/urls.py
from django.conf.urls import url
from . import views
# from django.contrib.admin.views.decorators import staff_member_required

app_name = 'post'

urlpatterns = [

    # URL links and their corresponding function in the views 

    url(r'^(?P<pk>[0-9]+)/$', views.Show_Post_View.as_view(), name='show-post'),
    url(r'^add-post/$', views.Post_Create.as_view(), name='add-post'),
    url(r'^(?P<pk>[0-9]+)/edit-post/$', views.Post_Update.as_view(), name='edit-post'),
    url(r'^(?P<pk>[0-9]+)/delete-post/$', views.Post_Delete.as_view(), name='delete-post'),
    url(r'^(?P<pk>[0-9]+)/like/$', views.Post_Like.as_view(), name='like-post'),
    url(r'^(?P<pk>[0-9]+)/post-likes-list/$', views.Post_Likes_List.as_view(), name='like-list-post'),
    url(r'^(?P<pk>[0-9]+)/post-vote-up/$', views.Post_Vote_Up.as_view(), name='vote-up-post'),
    url(r'^(?P<pk>[0-9]+)/post-vote-down/$', views.Post_Vote_Down.as_view(), name='vote-down-post'),
    url(r'^(?P<pk>[0-9]+)/report-post/$', views.Post_Report.as_view(), name='report-post'),
    url(r'^(?P<pk>[0-9]+)/disable-post/$', views.Post_Enable_Disable_Page.as_view(), name='disable-post'),
    url(r'^(?P<pk>[0-9]+)/disable-post-confirm/$', views.Post_Enable_Disable.as_view(), name='disable-post-confirm'),
    url(r'^(?P<pk>[0-9]+)/remove-post-flags/$', views.Post_Remove_Flags_Page.as_view(), name='remove-post-flags'),
    url(r'^(?P<pk>[0-9]+)/remove-post-flags-confirm/$', views.Post_Remove_Flags.as_view(), name='remove-post-flags-confirm'),
    url(r'^(?P<pk>[0-9]+)/open-comments/$', views.Post_Open_Comments.as_view(), name='open-comments'),
]

qa_forums/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from main.views import pageNotFound
from django.conf.urls import handler404, handler500
from main import views

urlpatterns = [

    url(r'^admin/', admin.site.urls),

    # include all the other URL files from the other apps 
    url(r'^', include('post.urls')),
    url(r'^', include('comment.urls')),
    url(r'^', include('reply.urls')),
    url(r'^', include('main.urls')),
    
    url(r'^page-not-found/', pageNotFound)
] 

# urls for any images uploaded by user
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# handling errors in urls
handler404 = views.error_404
handler500 = views.error_500

main/models.py
from django.db import models
from django.contrib.auth.models import User

# a model for storing the user's profile info in the database 
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    numOfPostsCommentsReplies = models.IntegerField(default=0)
    numberOfLikes = models.IntegerField(default=0)
    activationCode = models.CharField(max_length=30, blank=True)
    resetPasswordCode = models.CharField(max_length=30, blank=True)
    dateJoined = models.DateTimeField(auto_now=False, auto_now_add=True)
    profilePicture = models.ImageField(upload_to='profile_pictures', blank=True)

    # a string representation of the object stored 
    def __str__(self):
        return self.user.username

main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile
from .validators import validate_email, validate_name, validate_password

# creates the form used in the templates when creating a new user 
class UserForm(forms.ModelForm):

    # overiding the __init__ function to remove the form's help_text
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = None # help text: "Required. 150 characters or fewer...etc"

    # adding validators to the form fields 
    email = forms.EmailField(validators=[validate_email])
    password = forms.CharField(widget=forms.PasswordInput(), validators=[validate_password])
    first_name = forms.CharField(validators=[validate_name])
    last_name = forms.CharField(validators=[validate_name])

    class Meta():
        model = User 
        # fields to display to the user
        fields = ('first_name', 'last_name', 'username', 'email', 'password')

# creates the form used in the templates when creating a profile for a new user 
class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfile 
        fields = ('profilePicture',)

# creates the form used in the templates when editing a user 
class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(validators=[validate_name])
    last_name = forms.CharField(validators=[validate_name])

    class Meta():
        model = User 
        # fields to display to the user
        fields = ('first_name', 'last_name',)

# creates the form used in the templates when editing a profile for a user 
class UserProfileUpdateForm(forms.ModelForm):
    profilePicture = forms.ImageField(required=False)
    class Meta():
        model = UserProfile 
        fields = ('profilePicture',)

main/views.py
from random import randint
from django.views import generic
from django.shortcuts import render
from .models import UserProfile, User
from post.models import Post 
from comment.models import Comment
from reply.models import Reply
from django.urls import reverse
from main.forms import UserForm, UserProfileForm, UserUpdateForm, UserProfileUpdateForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.http import HttpResponse
from django.conf import settings
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from .validators import validate_password
import string
import random
from django.core.paginator import Paginator

# registers a new user, sends them an email and saves their profile in the database
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and  profile_form.is_valid():
            user = user_form.save(commit=False) # don't save it in the database yet 

            user.set_password(user.password) # set_password function ensures hashing before saving
            user.is_active = False
            user.save()

            profile = profile_form.save(commit=False) # don't save it in the database yet
            profile.user = user # sets the one to one relationship 
            profile.activationCode = randint(1000, 9999)

            if 'profilePicture' in request.FILES:
                profile.profilePicture = request.FILES['profilePicture']
                
            registered = True
            profile.save()

            # emailing the user using a html template. if the template doesn't work, a txt file gets used as an alternative 
            subject = 'Welcome! - Intelligent Q&A Forums'
            email_to = [user.email] 
            with open(settings.BASE_DIR + "/main/templates/main/authentication/sign_up_email.txt") as temp:
                sign_up_email = temp.read()
            email = EmailMultiAlternatives(
                subject=subject, 
                body=sign_up_email,
                from_email=settings.EMAIL_HOST_USER,
                to=email_to
            )
            html = get_template("main/authentication/sign_up_email.html").render({'user': user, 'activationCode': profile.activationCode})
            email.attach_alternative(html, "text/html")
            email.send()

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(request, 'main/authentication/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

# logs in an existing user 
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)

        if user: 
            if user.is_active:
                login(request, user)

                # creating a userProfile object for superuser when they log in for the first time. (admins are created through the command line so we have to manually create their userProfile)
                if user.is_superuser:
                    try:
                        userProfile = UserProfile.objects.get(user=user)
                    except UserProfile.DoesNotExist:
                        userProfile = UserProfile.objects.create(user=user)
                        userProfile.save()

                # url to redirect to after logging in
                url_to_redirect_to = request.POST.get('next_url')
                if url_to_redirect_to != 'None/':
                    return HttpResponseRedirect('/' + url_to_redirect_to)

                return HttpResponseRedirect(reverse('main:index'))
            else:
                return render(request, 'main/authentication/login.html', {'error': 'Sorry, unable to log you in.'})
        else:
            return render(request, 'main/authentication/login.html', {'error': 'Sorry, unable to log you in.'})
    else:
        url_to_redirect_to = request.GET.get('next')
        return render(request, 'main/authentication/login.html', {'next_url': url_to_redirect_to})

# activates a user that has just signed up
def activate(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        activationCode = request.POST.get('activationCode')
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = None 
        
        if user:
            userProfile = UserProfile.objects.get(user=user)

            if activationCode == userProfile.activationCode: 
                user.is_active = True 
                user.save()
                # changing the activationCode so the user won't be able to activate themselves when Admin disables them.
                userProfile.activationCode = randint(1000, 9999)
                userProfile.save()
                return render(request, 'main/authentication/activate.html', {'activation_success': 'Success! Your account is now activated!'})
            else: 
                return render(request, 'main/authentication/activate.html', {'error': 'Sorry, unable to activate your account.'})

        else:
            return render(request, 'main/authentication/activate.html', {'error': 'Sorry, unable to activate your account.'})
    else:
        return render(request, 'main/authentication/activate.html', {})

# resends the user's username via email 
def resend_username(request):
    if request.method == 'POST':
        email = request.POST.get('email')

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            user = None
        
        if user:
            subject = 'Your Username - Intelligent Q&A Forums'
            email_to = [user.email] 
            with open(settings.BASE_DIR + "/main/templates/main/authentication/forgot-username/resend_username_email.txt") as temp:
                resend_username_email = temp.read()
            email = EmailMultiAlternatives(
                subject=subject, 
                body=resend_username_email,
                from_email=settings.EMAIL_HOST_USER,
                to=email_to
            )
            html = get_template("main/authentication/forgot-username/resend_username_email.html").render({'user': user})
            email.attach_alternative(html, "text/html")
            email.send()

        return render(request, 'main/authentication/login.html', {'activation_success': 'If your email address is linked with an account, an email will be sent to you with your username.'})

    else:
        return render(request, 'main/authentication/forgot-username/resend-username.html', {})

# send the user an email with a passcode to reset their password
def reset_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            user = None
        
        if user:
            userProfile = UserProfile.objects.get(user=user)
            # resetPasswordCode is a combination of 15 different letters/numbers 
            userProfile.resetPasswordCode = "".join(random.choices(string.ascii_uppercase + string.digits, k=15))
            userProfile.save() 
            
            # emailing the user with their resetPasswordCode
            subject = 'Reset your Password - Intelligent Q&A Forums'
            email_to = [userProfile.user.email] 
            with open(settings.BASE_DIR + "/main/templates/main/authentication/forgot-password/reset_password_email.txt") as temp:
                reset_password_email = temp.read()
            email = EmailMultiAlternatives(
                subject=subject, 
                body=reset_password_email,
                from_email=settings.EMAIL_HOST_USER,
                to=email_to
            )
            html = get_template("main/authentication/forgot-password/reset_password_email.html").render({'userProfile': userProfile})
            email.attach_alternative(html, "text/html")
            email.send()

        return render(request, 'main/authentication/forgot-password/reset-password-auth.html', {'reset_password_email_sent': 'If the email address is correct, a temp code will be sent to you.'})

    else:
        return render(request, 'main/authentication/forgot-password/reset-password.html', {})

# authenticating the user to reset their password  
def reset_password_auth(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        temp_code = request.POST.get('temp_code')
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            user = None 
        
        if user:
            userProfile = UserProfile.objects.get(user=user)

            if email == userProfile.user.email and temp_code == userProfile.resetPasswordCode: 
                userProfile.resetPasswordCode = "".join(random.choices(string.ascii_uppercase + string.digits, k=15)) # change resetPasswordCode for security reasons
                userProfile.save()
                return render(request, 'main/authentication/forgot-password/reset-password-confirm.html', {'reset_user_auth': 'Success! You can now reset your password!', 'user': user})
            else: 
                return render(request, 'main/authentication/forgot-password/reset-password-auth.html', {'error': 'Sorry, unable to reset your password'})

        else:
            return render(request, 'main/authentication/forgot-password/reset-password-auth.html', {'error': 'Sorry, unable to reset your password'})
    else:

main/templates/main/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'allPosts/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

{% include "main/navigationbar.html" %}

<div class='wrapper'>
    {% if user_deleted %}
        <div class='toast-message'>{{user_deleted}}</div>
    {% endif %}
    {% if all_posts %}
        <h1>All Posts:</h1>
        <table class="postsTable">
            <tr>
                <th width='5%'></th>
                <th width='34%'>Post</th>
                <th width='24%'>Topic</th>
                <th width='24%'>Discussion Started By</th>
                <th width='13%'>Comments</th>
            </tr>
            {% for post in all_posts %}
                {% if not post.postDisabled %}
                    <tr>
                        <td class='text-wrap'>{% if post.postNumberOfVotes < 0 %}<i class="fas fa-angle-double-down"></i>{% else %}<i class="fas fa-angle-double-up"></i>{% endif %} <strong>{{post.postNumberOfVotes}}</strong></td>
                        <td class='text-wrap'><a href="{% url 'post:show-post' post.id %}">{{post.postTitle}}</a></td>
                        <td class='text-wrap'><a href="{% url 'main:topic' post.postTopicNoSpaces %}">{{post.postTopic}}</a></td>
                        <td class='text-wrap'><a href="{% url 'main:profile' post.postedBy %}" >{{post.postedBy.user.first_name}} {{post.postedBy.user.last_name}}</a></td>
                        <td class='text-wrap'>{{post.postNumberOfComments}}&nbsp;&nbsp;<i class="far fa-comment-alt"></i></td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>

        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}"><i class="far fa-arrow-alt-circle-left"></i></a>
                {% endif %}
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}"><i class="far fa-arrow-alt-circle-right"></i></a>
                {% endif %}
            </span>
        </div>

    {% else %}
        <h1>Welcome to Intelligent Q&#38;A Forums! </h1>
        <h2>Be the first one to write a post!</h2>
    {% endif %}
</div>

main/templates/main/navigationbar.html
{% load staticfiles %}
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'navigationbar/style.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">

<div class="navigationbar">
    <a href="{% url 'main:index'%}" class='logo wide-screen-logo'>Intelligent Q&#38;A Forums</a>
    <a href="{% url 'main:index'%}" class='logo narrow-screen-logo'>IQ&#38;AF</a>
    <a href="{% url 'main:topics'%}" class='wide-screen'><i class="fas fa-book"></i>&nbsp;<span>Topics</span></a>
    <a href="{% url 'main:topics'%}" class='narrow-screen'><i class="fas fa-book icon-only"></i></a>
    {% comment %} staff view (including admins)  {% endcomment %}
    {% if user.is_staff %}
        <a href="{% url 'main:flagged-posts'%}" class='wide-screen'><i class="fas fa-exclamation-circle"></i>&nbsp; Flagged Posts</a>
        <a href="{% url 'main:flagged-posts'%}" class='narrow-screen'><i class="fas fa-exclamation-circle icon-only"></i></a>
    {% endif %}
    {% comment %} admin only view {% endcomment %}
    {% if user.is_superuser %}
        <a href="{% url 'main:staff'%}" class='wide-screen'><i class="fas fa-users"></i></i>&nbsp; Users</a>
        <a href="{% url 'main:staff'%}" class='narrow-screen'><i class="fas fa-users icon-only"></i></i></a>
    {% endif %}
    {% comment %} logged in users views (including staff and admin) {% endcomment %}
    {% if user.is_authenticated %}
        <a style="float:right" href="{% url 'post:add-post'%}" class='wide-screen'><i class="fas fa-plus"></i>&nbsp; Add New Post</a>
        <a style="float:right" href="{% url 'post:add-post'%}" class='narrow-screen'><i class="fas fa-plus icon-only"></i></a>
    {% endif %}

    {% if user.is_authenticated %}
        <div style="float:right" class="dropdown">
            <button class="dropbtn wide-screen">Hey,&nbsp;
            <strong>
                {% if user.first_name %}
                    {{user.first_name}}
                {% else %}
                    User
                {% endif %}
            </strong>!&nbsp; <i class="fa fa-caret-down"></i></button>
            <button class="dropbtn narrow-screen"><i class="fas fa-ellipsis-h icon-only"></i></button>
            <div class="dropdown-content">
                <a href="{% url 'main:profile' user %}" class='wide-screen'><i class="fas fa-user"></i>&nbsp; My Profile</a>
                <a href="{% url 'main:profile' user %}" class='narrow-screen'><i class="fas fa-user icon-only"></i></a>
                <a href="{% url 'main:user-logout' %}" class='wide-screen'><i class="fas fa-sign-out-alt"></i>&nbsp; Logout</a>
                <a href="{% url 'main:user-logout' %}" class='narrow-screen'><i class="fas fa-sign-out-alt icon-only"></i></a>
            </div>
        </div> 
    {% else %}
        <a style="float:right" href="{% url 'main:register' %}" class='wide-screen'><i class="fas fa-user-plus"></i>&nbsp; Sign Up</a>
        <a style="float:right" href="{% url 'main:user-login' %}" class='wide-screen'><i class="fas fa-sign-in-alt"></i>&nbsp; Login</a>
        <a style="float:right" href="{% url 'main:register' %}" class='narrow-screen'><i class="fas fa-user-plus icon-only"></i>&nbsp;</a>
        <a style="float:right" href="{% url 'main:user-login' %}" class='narrow-screen'><i class="fas fa-sign-in-alt icon-only"></i>&nbsp;</a>
    {% endif %}

</div>

main/templates/main/page-not-found.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

{% include "main/navigationbar.html" %}

<div class='wrapper'>
    <h2>Page Not Found!</h2>
    <p>Sorry, the page you requested is currently unavailable.</p>
</div>

main/templates/main/staff.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'allPosts/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

{% include "main/navigationbar.html" %}

<div class='wrapper'>
    <h1>Admin Panel</h1>
    <hr/>
    <p>Change the users' permissions on the site to either staff/regular users, and Activate/Deactivate accounts.</p>
    <table class="postsTable">
        <tr>
            <th width='15%' class='text-wrap'>Username</th>
            <th width='25%'>Name &#38; Email</th>
            <th width='10%'>Staff</th>
            <th width='20%'>Update Staff Status</th>
            <th width='10%'>Active</th>
            <th width='20%'>Update Active Status</th>
        </tr>

        {% comment %} ADMINS {% endcomment %}
        {% for user in users %}
            {% if user.is_superuser %}
                <tr>
                    <td class='text-wrap'><a href="{% url 'main:profile' user %}" >{{user.username}}</a></td>
                    <td class='text-wrap'><div><b>{{user.first_name}} {{user.last_name}}</b></div><div><i>{{user.email}}</i></div></td>
                    <td class='text-wrap'>
                        <p style='color:green'><i class="fas fa-check-circle"></i></p>
                    </td>
                    <td class='text-wrap'>(Admin)</td>
                    <td class='text-wrap'>
                        <p style='color:green'><i class="fas fa-check-circle"></i></p>
                    </td>
                    <td class='text-wrap'>(Admin)</td>
                </tr>
            {% endif %}
        {% endfor %}

        {% comment %} OTHER TYPES OF USERS {% endcomment %}
        {% for user in users %}
            {% if not user.is_superuser %}
                <tr>
                    <td class='text-wrap'><a href="{% url 'main:profile' user %}" >{{user.username}}</a></td>
                    <td class='text-wrap'><div><b>{{user.first_name}} {{user.last_name}}</b></div><div><i>{{user.email}}</i></div></td>
                    <td>
                        {% if user.is_staff %}
                            <p style='color:green'><i class="fas fa-check-circle"></i></p>
                        {% else %}
                            <p style='color:red'><i class="fas fa-times-circle"></i></p>
                        {% endif %}
                    </td>
                    <td><a href="{% url 'main:update-staff' user.username %}">{% if user.is_staff %}Change to Regular User{% else %}Change to Staff{% endif %}</a></td>
                    <td>
                        {% if user.is_active %}
                            <p style='color:green'><i class="fas fa-check-circle"></i></p>
                        {% else %}
                            <p style='color:red'><i class="fas fa-times-circle"></i></p>
                        {% endif %}
                    </td>
                    <td><a href="{% url 'main:update-active' user.username %}">{% if user.is_active %}Change to Disabled{% else %}Change to Active{% endif %}</a></td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
</div>

main/templates/main/topic.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'allPosts/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

{% include "main/navigationbar.html" %}

<div class='wrapper'>
    {% if posts %}
        <h1 class='text-wrap'>{{topic}}:</h1>
        <table class="postsTable">
            <tr>
                <th width='10%'></th>
                <th width='40%'>Post</th>
                <th width='30%'>Discussion Started By</th>
                <th width='20%'>Comments</th>
            </tr>
            {% for post in posts %}
                <tr>
                    <td class='text-wrap'>{% if post.postNumberOfVotes < 0 %}<i class="fas fa-angle-double-down"></i>{% else %}<i class="fas fa-angle-double-up"></i>{% endif %} <strong>{{post.postNumberOfVotes}}</strong></td>
                    <td class='text-wrap'><a href="{% url 'post:show-post' post.id %}">{{post.postTitle}}</a></td>
                    <td class='text-wrap'><a href="{% url 'main:profile' post.postedBy %}" >{{post.postedBy.user.first_name}} {{post.postedBy.user.last_name}}</a></td>
                    <td class='text-wrap'>{{post.postNumberOfComments}}&nbsp;&nbsp;<i class="far fa-comment-alt"></i></td>
                </tr>
            {% endfor %}
        </table>

        <div class="pagination">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href="?page={{ posts.previous_page_number }}"><i class="far fa-arrow-alt-circle-left"></i></a>
                {% endif %}
                <span class="current">
                    Page {{ posts.number }} of {{ posts.paginator.num_pages }}
                </span>
                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}"><i class="far fa-arrow-alt-circle-right"></i></a>
                {% endif %}
            </span>
        </div>

    {% else %}
        <h1>Sorry, No Posts Available.</h1>
    {% endif %}
</div>